# Generated by Django 5.0.1 on 2025-04-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('inactive_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
