# Generated by Django 5.0.1 on 2025-11-05 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_leave_management', '0002_alter_employees_active_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_group_type', to='hostel_leave_management.listtypevalues'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_leave_management.department'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_leave_management.designation'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_type', to='hostel_leave_management.listtypevalues'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_type', to='hostel_leave_management.listtypevalues'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel_leave_management.location'),
        ),
    ]
