# Generated by Django 5.0.1 on 2025-11-05 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_leave_management', '0003_alter_employees_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_department', to='hostel_leave_management.department'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emp_designation', to='hostel_leave_management.designation'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='pay_frequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pay_frequency_type', to='hostel_leave_management.listtypevalues'),
        ),
    ]
