# Generated by Django 5.0.1 on 2025-11-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_leave_management', '0004_alter_employees_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='previous_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
