# Generated by Django 5.0.1 on 2025-11-14 01:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_leave_management', '0005_alter_employees_previous_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='userHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(max_length=100)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('user_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'user_headers',
            },
        ),
        migrations.CreateModel(
            name='userLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('create_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hostel_leave_management.userheaders')),
            ],
            options={
                'db_table': 'user_lines',
            },
        ),
    ]
