# Generated by Django 5.0.1 on 2025-11-14 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_leave_management', '0006_userheaders_userlines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userheaders',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='userlines',
            name='role_id',
        ),
        migrations.AddField(
            model_name='userheaders',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_employee', to='hostel_leave_management.employees'),
        ),
        migrations.AddField(
            model_name='userlines',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_role', to='hostel_leave_management.roles'),
        ),
        migrations.AlterField(
            model_name='userheaders',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_type', to='hostel_leave_management.listtypevalues'),
        ),
    ]
