# Generated by Django 5.0.1 on 2025-11-17 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel_leave_management', '0008_remove_userlines_header_remove_userlines_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userline',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelTable(
            name='userline',
            table='user_lines',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profiles',
        ),
    ]
