# Generated by Django 5.0.1 on 2025-10-21 03:18

import django.db.models.deletion
import django.utils.timezone
import hostel_leave_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BloodGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blood_groups',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=10)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('country_flag', models.ImageField(blank=True, null=True, upload_to=hostel_leave_management.models.country_flag_upload_path)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'countries',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('inactive_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'designations',
            },
        ),
        migrations.CreateModel(
            name='Lov',
            fields=[
                ('list_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('inactive_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_flag', models.CharField(default='N', max_length=1)),
            ],
            options={
                'db_table': 'lov',
            },
        ),
        migrations.CreateModel(
            name='ProjectsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('project_description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'projects_header',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='ListTypeValues',
            fields=[
                ('list_type_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('list_code', models.CharField(blank=True, max_length=150, null=True)),
                ('list_value', models.CharField(blank=True, max_length=150, null=True)),
                ('order_sequence', models.IntegerField(blank=True, null=True)),
                ('short_description', models.CharField(blank=True, max_length=255, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('inactive_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated_by', models.IntegerField(blank=True, null=True)),
                ('last_updated_date', models.DateTimeField(blank=True, null=True)),
                ('deleted_flag', models.CharField(default='N', max_length=1)),
                ('list_type_id', models.ForeignKey(blank=True, db_column='list_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='hostel_leave_management.lov')),
            ],
            options={
                'db_table': 'list_type_values',
            },
        ),
        migrations.CreateModel(
            name='ProjectsLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_title', models.CharField(max_length=255)),
                ('line_description', models.TextField(blank=True, null=True)),
                ('active_flag', models.CharField(default='Y', max_length=1)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('last_updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hostel_leave_management.projectsheader')),
            ],
            options={
                'db_table': 'projects_line',
            },
        ),
    ]
